import { useState } from 'react'
import { useFetch } from '@/hooks/useFetch'
import { useLanguage } from '@/components/i18n/LanguageProvider'
import { operationsPost } from '@/lib/operationsClient'
import type { EvidenceNode, ShipmentDetail } from '@/contracts/caseDetail'
import { evidenceGraph } from '@/contracts/caseDetail'
import { Graph } from '@/components/artifacts/Graph'
import { CaseWorkflowBadge } from '@/components/operations/StatusBadge'
import { LoadingState } from '@/components/operations/LoadingState'
import { ErrorState } from '@/components/operations/ErrorState'
import { CaseTransition } from '@/components/operations/CaseTransition'
import { ShipmentRouteMap } from '@/components/operations/ShipmentRouteMap'
import { useOperationsPage } from '@/hooks/useOperationsPage'
import { useCursorPage } from '@/hooks/useCursorPage'
import { Timeline } from '@/components/operations/Timeline'
import { CursorPagination } from '@/components/operations/Pagination'
import { adaptAudit, pageQuery, type ApiAuditEvent } from '@/adapters/operationsApi'

const SECTIONS = ['overview', 'evidence', 'diagnosis', 'recommendation', 'review', 'map', 'history'] as const
type Section = typeof SECTIONS[number]
function CaseAudit({ caseId }: { caseId: string }) {
  const { t } = useLanguage()
  const pager = useCursorPage()
  const [limit, setLimit] = useState(25)
  const { data, loading, error, refetch } = useOperationsPage<ApiAuditEvent>(`/audit?${pageQuery({ case_id: caseId, limit, cursor: pager.cursor })}`)
  if (loading) return <LoadingState label={t('ops.audit.loading')} />
  if (error) return <ErrorState onRetry={refetch} />
  return <div className="space-y-3"><h3 className="font-semibold">{t('ops.audit.title')}</h3>{data?.items.length ? <Timeline events={data.items.map(adaptAudit)} /> : <p className="text-sm text-muted-foreground">{t('ops.audit.emptyTitle')}</p>}<CursorPagination total={data?.filtered_total ?? 0} limit={limit} cursorStart={pager.offset} nextCursor={data?.next_cursor ?? null} prevCursor={pager.hasPrevious ? 'visited' : null} onNext={() => pager.next(data?.next_cursor, limit)} onPrev={() => pager.previous(limit)} onLimitChange={n => { setLimit(n); pager.reset() }} /></div>
}

export function OperationsCaseDetail({ caseId, shipmentId, onBack }: { caseId?: string; shipmentId: string; onBack: () => void }) {
  const { t, isArabic, rootCauseLabel, entityLabel, propertyLabel } = useLanguage()
  const { data, loading, error, refetch } = useFetch<ShipmentDetail>(caseId ? `/cases/${encodeURIComponent(caseId)}` : `/shipments/${encodeURIComponent(shipmentId)}/context`)
  const [pending, setPending] = useState(false)
  const [actionError, setActionError] = useState<string | null>(null)
  const [outcomeType, setOutcomeType] = useState('')
  const [success, setSuccess] = useState('')
  const [evidenceIds, setEvidenceIds] = useState<string[]>([])
  const [section, setSection] = useState<Section>('overview')
  const [mapMode, setMapMode] = useState<'map' | 'graph'>('map')
  // Fresh evidence assessment is a proposal, never the mutable workflow authority.
  const state = data?.workflow_state
  const command = async (action: string, body: Record<string, unknown> = {}) => {
    if (!caseId || pending) return
    setPending(true); setActionError(null)
    try { await operationsPost(`/cases/${encodeURIComponent(caseId)}/${action}`, { ...body, idempotency_key: crypto.randomUUID(), expected_version: data?.state_version }); refetch() }
    catch (e) { setActionError(e instanceof Error ? e.message : 'Request failed') }
    finally { setPending(false) }
  }
  return <section className="mx-auto max-w-6xl space-y-4" dir={isArabic ? 'rtl' : 'ltr'}>
    <button type="button" onClick={onBack} className="rounded-lg border border-border px-3 py-2">{t('ops.workspace.back')}</button>
    <button type="button" disabled={pending || loading} onClick={refetch} className="ms-2 rounded-lg border border-border px-3 py-2 disabled:opacity-50">{t('explore.refresh')}</button>
    <h2 className="font-mono text-lg" dir="ltr">{shipmentId}</h2>
    {loading ? <LoadingState label={t('explore.loading')} /> : error || (data && !data.evidence?.nodes) ? <ErrorState onRetry={refetch} /> : data && <>
      {data.synthetic && <p className="text-xs font-semibold text-chart-warning">{t('ops.simulation.label')}</p>}
      {state && <CaseWorkflowBadge state={state} />}
      {state && ['OPEN', 'INVESTIGATING', 'RECOMMENDATION_READY', 'AWAITING_APPROVAL', 'ACTION_INITIATED', 'AWAITING_OUTCOME', 'RESOLVED'].includes(state) && <CaseTransition state={state} />}
      {caseId && (state === 'OPEN' || state === 'REOPENED') && <button type="button" disabled={pending || data.state_version == null} onClick={() => void command('investigate')} className="rounded-lg bg-primary px-3 py-2 text-primary-foreground disabled:opacity-50">{t('ops.case.openInvestigation')}</button>}
      {!caseId && <p className="text-sm text-muted-foreground">{t('ops.workspace.evidenceOnly')}</p>}
      {caseId && (state === 'AWAITING_APPROVAL' || state === 'HUMAN_REVIEW') && <div className="flex flex-wrap gap-2">{(['approve', 'reject', 'request_evidence', 'escalate'] as const).map(decision => <button key={decision} type="button" disabled={pending || data.state_version == null || (decision === 'approve' && !data.recommendation_id)} onClick={() => void command('decision', { decision })} className="rounded-lg border border-border bg-card px-3 py-2 disabled:opacity-50">{t(`ops.actions.${decision}`)}</button>)}</div>}
      {caseId && state && ['RESOLVED', 'REJECTED', 'ESCALATED', 'NEEDS_EVIDENCE'].includes(state) && <button type="button" disabled={pending || data.state_version == null} onClick={() => void command('decision', { decision: 'reopen' })} className="rounded-lg border border-border px-3 py-2 disabled:opacity-50">{t('ops.actions.reopen')}</button>}
      {actionError && <ErrorState message={t('ops.error.action')} onRetry={() => { setActionError(null); refetch() }} />}
      <div className="flex flex-wrap gap-2 border-b border-border pb-3" role="group" aria-label={t('ops.workspace.sections')}>
        {SECTIONS.map(key => <button key={key} type="button" aria-pressed={section === key} onClick={() => setSection(key)} className={`rounded-lg px-3 py-2 text-sm focus-visible:outline-2 focus-visible:outline-ring ${section === key ? 'bg-primary text-primary-foreground' : 'border border-border bg-card text-muted-foreground'}`}>{t(`ops.workspace.${key}`)}</button>)}
      </div>
      {section === 'overview' && <div className="grid gap-3 sm:grid-cols-3">{[['asOf', data.as_of], ['assessedAt', data.investigated_at], ['mode', t('ops.workspace.ruleMode')]].map(([key, value]) => <div key={key} className="rounded-xl border border-border bg-card p-3"><p className="text-xs text-muted-foreground">{t(`ops.workspace.${key}`)}</p><p className="mt-1 break-words text-sm" dir={key === 'mode' ? 'auto' : 'ltr'}>{value ?? '—'}</p></div>)}</div>}
      {section === 'evidence' && <div className="space-y-3">
        <p className="text-sm text-muted-foreground">{t('ops.workspace.evidenceCount', { nodes: data.evidence.nodes.length, edges: data.evidence.edges.length })}</p>
        {Object.entries(data.evidence.nodes.reduce<Record<string, EvidenceNode[]>>((groups, n) => { (groups[n.kind] ??= []).push(n); return groups }, {})).map(([kind, nodes]) => <details key={kind} className="rounded-xl border border-border bg-card p-3"><summary className="cursor-pointer font-medium">{entityLabel(kind)} <span className="text-xs text-muted-foreground">({nodes?.length})</span></summary><div className="mt-3 space-y-2">{nodes?.map(n => <div key={n.id} className="rounded-lg bg-muted/40 p-3"><p className="break-all font-mono text-xs" dir="ltr">{n.id}</p><dl className="mt-2 grid gap-x-4 gap-y-1 text-xs sm:grid-cols-2">{Object.entries(n.properties).filter(([k,v]) => ['event_type','occurred_at','recorded_at','earliest_at','latest_at','package_id','from_holder_id','to_holder_id','vehicle_id','driver_id','status','result','report_code','weight_kg','address_text','verification_status'].includes(k) && v != null).map(([k,v]) => <div key={k} className="min-w-0"><dt className="text-muted-foreground">{propertyLabel(k)}</dt><dd className="break-words" dir="auto">{String(v)}</dd></div>)}</dl></div>)}</div></details>)}
      </div>}
      {section === 'recommendation' && data.recommendation && <div className="rounded-xl border border-border bg-card p-4"><h3 className="font-semibold">{t('ops.workspace.recommendation')}</h3><p className="mt-2" dir="auto">{isArabic ? data.recommendation.action_ar ?? data.recommendation.action : data.recommendation.action_en ?? data.recommendation.action}</p><p dir="auto">{isArabic ? data.recommendation.summary_ar ?? data.recommendation.summary_en : data.recommendation.summary_en ?? data.recommendation.summary_ar}</p></div>}
      {section === 'review' && data.review && <div className="space-y-2 rounded-xl border border-border bg-card p-4"><h3 className="font-semibold">{t('ops.workspace.review')}</h3><p>{t(`ops.review.${data.review.verdict}`)}</p><p dir="auto">{isArabic ? data.review.summary_ar ?? data.review.summary_en ?? data.review.feedback : data.review.summary_en ?? data.review.summary_ar ?? data.review.feedback}</p><p className="text-xs text-muted-foreground">{t('ops.transition.noSkipToResolved')}</p></div>}
      {section === 'review' && !!data.run?.result?.trace?.length && <ol className="space-y-3">{data.run.result.trace.map(item => <li key={item.iteration} className="space-y-2 rounded-xl border border-border bg-card p-4"><p className="text-xs text-muted-foreground">{t('ops.workspace.reviewRound', { round: item.iteration + 1 })}</p><p className="font-medium">{t(`ops.review.${item.review.verdict}`)}</p><p dir="auto">{isArabic ? item.proposal?.action_ar ?? (item.review.verdict === 'reject' ? t('ops.workspace.rejectedGpsProposal') : item.proposal?.action) : item.proposal?.action_en ?? item.proposal?.action}</p><p className="text-sm text-muted-foreground" dir="auto">{isArabic ? item.review.verdict === 'reject' ? t('ops.workspace.gpsGuard') : t('ops.review.accept') : item.review.feedback}</p></li>)}</ol>}
      {(section === 'overview' || section === 'recommendation') && !!data.decisions?.length && <section className="space-y-2 rounded-xl border border-border p-3"><h3 className="font-semibold">{t('ops.trace.human_decision')}</h3>{data.decisions.map((d, i) => <p key={i}>{t(`ops.actions.${d.decision}`)} <time className="text-xs text-muted-foreground" dir="ltr">{d.occurred_at}</time></p>)}</section>}
      {(section === 'overview' || section === 'recommendation') && !!data.executions?.length && <section className="space-y-2 rounded-xl border border-border p-3"><h3 className="font-semibold">{t('ops.workspace.actionReceipts')}</h3>{data.executions.map((e, i) => <p key={i} className="break-all font-mono text-xs" dir="ltr">{e.receipt_ref}</p>)}<p className="text-xs text-muted-foreground">{t('ops.actions.outcomeHint')}</p></section>}
      {(section === 'overview' || section === 'diagnosis') && <section className="space-y-3 rounded-xl border border-border bg-card p-4"><h3 className="font-semibold">{t('ops.workspace.diagnosis')}</h3>{data.reasoning?.diagnoses?.length ? data.reasoning.diagnoses.map((d, i) => <div key={i}><p className="font-medium">{rootCauseLabel(d.code ?? d.category ?? '')}</p><p dir="auto" className="text-sm text-muted-foreground">{isArabic ? d.summary_ar ?? d.explanation_ar ?? d.explanation_en ?? d.summary : d.summary_en ?? d.explanation_en ?? d.explanation_ar ?? d.summary}</p>{section === 'diagnosis' && <p className="mt-2 break-all font-mono text-xs text-muted-foreground" dir="ltr">{d.evidence_ids?.join(' · ')}</p>}</div>) : <p className="text-sm text-muted-foreground">{t('ops.workspace.noDiagnosis')}</p>}</section>}
      {section === 'diagnosis' && !!data.reasoning?.assessment?.expected_vs_actual?.length && <section className="space-y-3 rounded-xl border border-border bg-card p-4"><h3 className="font-semibold">{t('ops.workspace.journey')}</h3>{data.reasoning.assessment.expected_vs_actual.filter(m => m.milestone_id).map(m => <div key={m.milestone_id} className="grid gap-2 rounded-lg bg-muted/40 p-3 text-xs sm:grid-cols-3"><p className="break-all font-mono" dir="ltr">{m.milestone_id}</p><p>{t('ops.workspace.expectedBy')} <time dir="ltr">{m.latest_at}</time></p><p>{t(m.missing_due ? 'ops.workspace.missing' : m.late ? 'ops.workspace.late' : 'ops.workspace.observed')} <time dir="ltr">{m.actual_at ?? '—'}</time></p></div>)}</section>}
      {section === 'overview' && state === 'AWAITING_OUTCOME' && caseId && <section className="space-y-3 rounded-xl border border-border p-3">
        <h3 className="font-semibold">{t('ops.actions.observe')}</h3><p className="text-xs text-muted-foreground">{t('ops.actions.outcomeHint')}</p>
        <div className="flex flex-wrap gap-3"><label>{t('ops.actions.outcomeType')} <select value={outcomeType} onChange={e => setOutcomeType(e.target.value)} className="rounded border border-border bg-card p-2"><option value="">{t('ops.actions.choose')}</option>{['delivery_verified', 'address_corrected', 'barcode_corrected', 'weight_remeasured', 'returned_to_depot', 'dispute_unresolved', 'insufficient_evidence'].map(type => <option key={type} value={type}>{t(`ops.outcomes.${type}`)}</option>)}</select></label><label>{t('ops.actions.observedResult')} <select value={success} onChange={e => setSuccess(e.target.value)} className="rounded border border-border bg-card p-2"><option value="">{t('ops.actions.choose')}</option><option value="true">{t('ops.actions.success')}</option><option value="false">{t('ops.actions.failure')}</option></select></label></div>
        <fieldset className="max-h-48 overflow-y-auto rounded border border-border p-2"><legend className="px-1 text-sm">{t('ops.actions.evidence')}</legend>{data.evidence.nodes.filter(n => ['DeliveryProof', 'AuthenticationEvidence', 'SignatureEvidence', 'PhotoEvidence', 'HandoffEvidence', 'CustodyEvent', 'ScanEvent', 'WeightObservation', 'AddressVersion', 'LocationPin', 'RecipientReport', 'DeliveryAttempt', 'DepotReconciliation'].includes(n.kind)).map(n => <label key={n.id} className="flex items-center gap-2 py-1 text-xs"><input type="checkbox" checked={evidenceIds.includes(n.id)} onChange={e => setEvidenceIds(ids => e.target.checked ? [...ids, n.id] : ids.filter(id => id !== n.id))} /><span dir="ltr" className="min-w-0 break-all">{n.id}</span><span>{entityLabel(n.kind)}</span></label>)}</fieldset>
        <button type="button" disabled={pending || data.state_version == null || !outcomeType || !success || !evidenceIds.length} onClick={() => void command('outcomes', { outcome_type: outcomeType, success: success === 'true', evidence_ids: evidenceIds })} className="rounded-lg border border-border px-3 py-2 disabled:opacity-50">{t('ops.actions.observe')}</button>
      </section>}
      {section === 'overview' && data.outcome && <section className="space-y-2 rounded-xl border border-border p-3"><h3 className="font-semibold">{t('ops.trace.outcome')}</h3><p>{t(`ops.actions.${data.outcome.invalidated ? 'invalidated' : data.outcome.verification_status === 'VERIFIED' ? 'verified' : 'observed'}`)}</p><p className="text-xs text-muted-foreground">{t('ops.actions.outcomeHint')}</p>{state === 'AWAITING_OUTCOME' && !data.outcome.invalidated && data.outcome.verification_status === 'OBSERVED' && (data.outcome.outcome_id ?? data.outcome.id) && <button type="button" disabled={pending || data.state_version == null} onClick={() => void command(`outcomes/${encodeURIComponent(data.outcome!.outcome_id ?? data.outcome!.id!)}/verify`)} className="rounded-lg border border-border px-3 py-2 disabled:opacity-50">{t('ops.actions.verify')}</button>}</section>}
      {section === 'recommendation' && <section className="space-y-2 rounded-xl border border-border p-3"><h3 className="font-semibold">{t('ops.workspace.proposedActions')}</h3>{data.reasoning?.recommendations?.map((r, i) => <div key={i} dir="auto"><p>{isArabic ? r.action_ar ?? r.action : r.action_en ?? r.action}</p><p className="text-sm text-muted-foreground">{isArabic ? r.explanation_ar ?? r.explanation_en ?? r.rationale : r.explanation_en ?? r.explanation_ar ?? r.rationale}</p></div>)}<p className="text-xs text-muted-foreground">{t('ops.transition.noSkipToResolved')}</p></section>}
      {section === 'map' && <div className="space-y-3"><div role="group" aria-label={t('explore.lens')} className="flex gap-2">{(['map', 'graph'] as const).map(mode => <button key={mode} type="button" aria-pressed={mapMode === mode} onClick={() => setMapMode(mode)} className="rounded-lg border border-border px-3 py-2 text-sm">{t(`explore.${mode}`)}</button>)}</div><div className="h-[520px] min-h-80 overflow-hidden rounded-xl border border-border">{mapMode === 'graph' ? <Graph graph={evidenceGraph(data)} /> : <ShipmentRouteMap detail={data} />}</div></div>}
      {section === 'history' && <div className="space-y-5">{caseId && <CaseAudit caseId={caseId} />}<section className="space-y-2 rounded-xl border border-border p-3"><h3 className="font-semibold">{t('ops.trace.similar_cases')}</h3><p className="text-xs text-muted-foreground">{t('ops.outcomeMetrics.syntheticCaution')}</p>{(data.reasoning?.precedents ?? data.precedents ?? []).map((p, i) => <details key={i} className="rounded-lg border border-border p-3"><summary className="cursor-pointer text-sm"><span className="font-mono" dir="ltr">{p.shipment_id}</span> · {p.success == null ? t('intake.stages.retrieve.pending') : p.success ? t('ops.outcomeMetrics.succeeded') : t('ops.outcomeMetrics.failed')}</summary><p className="mt-2" dir="auto">{isArabic && p.synthetic ? t('ops.workspace.syntheticFollowup') : p.action}</p><time dir="ltr" className="text-xs text-muted-foreground">{p.verified_at}</time><p className="break-all font-mono text-xs text-muted-foreground" dir="ltr">{p.evidence_ids?.join(' · ')}</p></details>)}</section></div>}
    </>}
  </section>
}
